name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.PYPI_USERNAME }}
      PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Publish package
        run: |
          pip install poetry
          poetry build
          poetry publish --username $USERNAME --password $PASSWORD
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build docs
        run: |
          pip install poetry
          poetry install
          poetry run etc/builddocs
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build
          force_orphan: true
